### PR TITLE
Hkatz/pretty print resources (Alternate Fix #78)

### LINKED ISSUE #78: Make units consistent
If the units are currently set in e.g. `Mi`, we should round the recommendation (which seems to always be in `k` for memory).

This way, the dashboard will be more readable (no more `128Mi < 262144k`), and any copy/pasted config will stick to the user's current unit conventions.

Screen Shot 2019-10-15 at 10 58 00 AM

### PR DESCRIPTION
**Pull request by hjkatz**
Hello!

I know that we've been chatting back and forth a bit about us sharing these PRs and development with y'all upstream, well here's the 1st PR of many!

## Background Context:

Squarespace forked the Goldilocks repo internally back in October 2019. I've been pretty actively working on our internal fork since then. So I have a bunch of commits and PRs that will be coming over the next few days/weeks that have lots of changes to the repo. Hopefully, y'all like them!

## This PR

One of the first issues we tackled in our fork was #78, however instead of approaching this issue from the client (templates) side, we approached if from the server (summary) side of things. The reason I'm reverting the commits made by @mgoodhart5 is that in a future PR I made significant changes to the `pkg/dashboard` which is essentially a rewrite. The changes in that future PR would be _extremely_ messy to view if I just blindly applied them and tried to resolve the merge conflicts. 

So my suggestion is that we first revert this 1 commit, then merge this PR and all of my future PRs, then we can reevaluate how to best solve #78 and either re-revert/apply Mary's changes, or keep mine. I'm not against either, I'm just looking for the easy path to get our changes back upstream!

Let me know what you think, and let's take this 1 PR at a time :)

### CODE REVIEW

**Comment by hjkatz** [comment]
@mgoodhart5 I don't want to come off as trying to step on your changes or the work that you put in for #78. I think your solution is a great one and honestly might be better. This PR is made in good faith that after this flurry of PRs we can come back and re-apply your changes over mine or whatever at that time.

**Comment by sudermanjr** [comment]
@hjkatz Thanks! Looking forward to these.  I should have a working e2e fix in place soon so that we can e2e test your PRs .

**Comment by sudermanjr** [comment]
@hjkatz Would you mind rebasing this on master so we can test out e2e testing for external PRs?

**Comment by hjkatz** [comment]
@sudermanjr I've pulled in your latest `master` to my fork's `master` and then rebased this branch off of that. Let me know if you need anything else. (Also I'll be in the call for office hours today so we can chat then too.)

**Pull request merged**
