### PR TITLE
Issue 84 support daemonsets

### PR DESCRIPTION
**Pull request by raspberrypython**
👋 I've been needing support for daemonsets and statefulsets so I thought I'd tackle the daemonset ticket first.
The changes I've made should make it easier to add statefulsets which I'll aim to do hot on the heals of this merge if you find it acceptable.

### CODE REVIEW

**Comment by raspberrypython** [comment]
I realised you asked for a flag to enable daemonsets on the controller, thats been added now:
--enable-daemonset-controller

**Comment by sudermanjr** [comment]
First glance this is looking really great. Thanks!! I will be reviewing in more detail in the next couple days, along with doing some tests.

**Comment by raspberrypython** [comment]
fwiw my StatefulSets branch can be found [here](https://github.com/raspberrypython/goldilocks/tree/issue_96_Support_StatefulSets) which extends the work done with daemonsets.
I'll PR that branch in once this PR is merged & any comments addressed

**Comment by nmizeb** [comment]
Hello @raspberrypython , 

Any updates for Daemonse-controller ? 
thanks

**Comment by raspberrypython** [comment]
Unfortunately the refactoring PR that got merged has made it rather difficult to merge into my changes. In fact the code has become more tightly coupled to deployments only. Frankly
I’ve not had the time to start again from scratch.

**Comment by sudermanjr** [comment]
@raspberrypython sorry about that. I will go ahead and close this and we can re-visit once the summary refactor is done.

**Pull request closed without merging**
